[2025-04-16T18:36:25.892+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-16T18:36:25.950+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: plusvalia_pipeline.extract_avaluos manual__2025-04-16T18:36:21.570656+00:00 [queued]>
[2025-04-16T18:36:25.964+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: plusvalia_pipeline.extract_avaluos manual__2025-04-16T18:36:21.570656+00:00 [queued]>
[2025-04-16T18:36:25.965+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-04-16T18:36:26.097+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_avaluos> on 2025-04-16 18:36:21.570656+00:00
[2025-04-16T18:36:26.113+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'plusvalia_pipeline', 'extract_avaluos', 'manual__2025-04-16T18:36:21.570656+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/plusvalia_pipeline_dag.py', '--cfg-path', '/tmp/tmpgmjcj993']
[2025-04-16T18:36:26.121+0000] {standard_task_runner.py:91} INFO - Job 2: Subtask extract_avaluos
[2025-04-16T18:36:26.123+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=183) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-16T18:36:26.127+0000] {standard_task_runner.py:63} INFO - Started process 185 to run task
[2025-04-16T18:36:26.352+0000] {task_command.py:426} INFO - Running <TaskInstance: plusvalia_pipeline.extract_avaluos manual__2025-04-16T18:36:21.570656+00:00 [running]> on host aa358234e421
[2025-04-16T18:36:26.575+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Brayan Miranda' AIRFLOW_CTX_DAG_ID='plusvalia_pipeline' AIRFLOW_CTX_TASK_ID='extract_avaluos' AIRFLOW_CTX_EXECUTION_DATE='2025-04-16T18:36:21.570656+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-16T18:36:21.570656+00:00'
[2025-04-16T18:36:26.578+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-16T18:36:26.824+0000] {logging_mixin.py:188} INFO - Extrayendo aval√∫os desde PDF...
[2025-04-16T18:36:26.828+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-16T18:36:26.829+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/etl/extract_avaluos.py", line 18, in extract_avaluos
    config = yaml.safe_load(file)
             ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/yaml/__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/yaml/composer.py", line 64, in compose_node
    if self.check_event(AliasEvent):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
                         ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/yaml/parser.py", line 449, in parse_block_mapping_value
    if not self.check_token(KeyToken, ValueToken, BlockEndToken):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/home/airflow/.local/lib/python3.12/site-packages/yaml/scanner.py", line 251, in fetch_more_tokens
    return self.fetch_double()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/yaml/scanner.py", line 655, in fetch_double
    self.fetch_flow_scalar(style='"')
  File "/home/airflow/.local/lib/python3.12/site-packages/yaml/scanner.py", line 666, in fetch_flow_scalar
    self.tokens.append(self.scan_flow_scalar(style))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/yaml/scanner.py", line 1149, in scan_flow_scalar
    chunks.extend(self.scan_flow_scalar_non_spaces(double, start_mark))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/yaml/scanner.py", line 1223, in scan_flow_scalar_non_spaces
    raise ScannerError("while scanning a double-quoted scalar", start_mark,
yaml.scanner.ScannerError: while scanning a double-quoted scalar
  in "/opt/airflow/config/config.yaml", line 10, column 18
found unknown escape character 's'
  in "/opt/airflow/config/config.yaml", line 10, column 28
[2025-04-16T18:36:26.855+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=plusvalia_pipeline, task_id=extract_avaluos, run_id=manual__2025-04-16T18:36:21.570656+00:00, execution_date=20250416T183621, start_date=20250416T183625, end_date=20250416T183626
[2025-04-16T18:36:26.995+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 2 for task extract_avaluos (while scanning a double-quoted scalar
  in "/opt/airflow/config/config.yaml", line 10, column 18
found unknown escape character 's'
  in "/opt/airflow/config/config.yaml", line 10, column 28; 185)
[2025-04-16T18:36:27.020+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-04-16T18:36:27.083+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-16T18:36:27.087+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
